version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
      - '80:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 5
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-web-app
    ports:
      - '8080:8080'
    volumes:
      - ./website:/app
    environment:
      - PORT=8080
    depends_on:
      - apache
